# Generated by Django 3.2.8 on 2022-01-19 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'installation_resource',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='domains',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='etats',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subdomains',
        ),
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poked', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='poked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'poke',
            },
        ),
    ]
