# Generated by Django 3.2.8 on 2022-01-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0002_auto_20220119_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
