# Generated by Django 3.2.8 on 2022-01-19 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0003_poke_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 19, 23, 24, 7, 617291)),
            preserve_default=False,
        ),
    ]
