# Generated by Django 3.2.8 on 2022-01-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0004_profile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
