# Generated by Django 4.0.1 on 2022-02-08 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appServers', '0004_server_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='project',
        ),
        migrations.AddField(
            model_name='server',
            name='project',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='appServers.project'),
            preserve_default=False,
        ),
    ]
